import Head from 'next/head'
import { Benefits } from '../components/Benefits'
import { ChooseOrigin } from '../components/ChooseOrigin'
import { Footer } from '../components/Footer'
import { Header } from '../components/Header'
import { Slide } from '../components/Slide'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet" />
      </Head>

      <Header />
      <main>
        <Benefits />

        <ChooseOrigin />

        <Slide />
      </main>

      <Footer />
    </div>
  )
}
